import fs from "node:fs/promises";
import path from "node:path";
import { OpLog, ensureDir, readJson, pathExists } from "../util.js";

export interface VfxBreedingOptions {
  presetA: string;
  presetB: string;
  outputDir: string;
  childName?: string;
  mutationRate?: number;
}

export interface VfxBreedResult {
  ok: boolean;
  childName: string;
  childPresetPath: string;
  inheritedTraits: Record<string, string>;
  prompt: string;
}

type PresetRecord = Record<string, unknown>;

export class VfxBreeding {
  constructor(private readonly log: OpLog) {}

  async breed(opts: VfxBreedingOptions): Promise<VfxBreedResult> {
    await ensureDir(opts.outputDir);
    const presetA = await this.loadPreset(opts.presetA, "A");
    const presetB = await this.loadPreset(opts.presetB, "B");
    const childName = opts.childName ?? `${this.nameOf(opts.presetA)}_${this.nameOf(opts.presetB)}_Hybrid`;
    const mutationRate = Math.max(0, Math.min(opts.mutationRate ?? 0.15, 1));

    const child = this.crossPreset(childName, presetA, presetB, mutationRate);
    const childPresetPath = path.join(opts.outputDir, `${childName.replace(/[^A-Za-z0-9_-]/g, "_")}.vfx.json`);
    await fs.writeFile(childPresetPath, JSON.stringify(child, null, 2), "utf8");

    const inheritedTraits = {
      colorRamp: "presetA",
      timingCurve: "presetB",
      particleBehavior: "mixed",
      mutationRate: mutationRate.toString(),
    };

    const prompt = [
      `Generate an After Effects VFX preset named ${childName}.`,
      "Inherit color ramp and glow language from preset A.",
      "Inherit timing curve and impact rhythm from preset B.",
      `Apply ${Math.round(mutationRate * 100)}% procedural mutation to particle scale, turbulence, and opacity decay.`,
    ].join(" ");

    this.log.info(`Hybrid VFX preset written: ${childPresetPath}`);
    return { ok: true, childName, childPresetPath, inheritedTraits, prompt };
  }

  private async loadPreset(presetPathOrName: string, label: string): Promise<PresetRecord> {
    if (await pathExists(presetPathOrName)) {
      this.log.info(`Loading preset ${label}: ${presetPathOrName}`);
      return readJson<PresetRecord>(presetPathOrName);
    }
    this.log.warn(`Preset ${label} file not found; treating input as preset name`);
    return {
      name: presetPathOrName,
      colorRamp: ["#ffffff", "#66ccff", "#001133"],
      timing: { attack: 0.12, sustain: 0.35, decay: 0.8 },
      particles: { count: 160, turbulence: 0.4, spread: 0.65 },
      glow: { intensity: 0.8, radius: 32 },
    };
  }

  private crossPreset(childName: string, a: PresetRecord, b: PresetRecord, mutationRate: number): PresetRecord {
    const mutation = Math.round(mutationRate * 100) / 100;
    return {
      name: childName,
      lineage: { presetA: a.name ?? "presetA", presetB: b.name ?? "presetB" },
      colorRamp: a.colorRamp ?? a.palette ?? ["#ffffff", "#66ccff"],
      timing: b.timing ?? b.curves ?? { attack: 0.1, sustain: 0.4, decay: 0.7 },
      particles: {
        ...(typeof a.particles === "object" && a.particles ? a.particles : {}),
        ...(typeof b.particleBehavior === "object" && b.particleBehavior ? b.particleBehavior : {}),
        mutation,
      },
      glow: b.glow ?? a.glow ?? { intensity: 0.75, radius: 28 },
      generatedAt: new Date().toISOString(),
      motionPilot: {
        tool: "vfx_breeding",
        note: "Hybrid preset generated by crossing color, timing, particle behavior, and mutation traits.",
      },
    };
  }

  private nameOf(value: string): string {
    return path.basename(value, path.extname(value)).replace(/[^A-Za-z0-9_-]/g, "_");
  }
}
